### ISSUE TITLE
Informance issue

### ISSUE THREAD

**Issue by pooya-mohammadi** [aliaminibagh/Facial-emotion-recognition-FastAPI-service#2]
https://github.com/aliaminibagh/Facial-emotion-recognition-FastAPI-service/blob/eddd422f799023e536c720d16ab91fc7fbb99a13/base_app.py#L68

At line 68, you can simply read the content of the file and read it using `cv2`. This approach prevents saving the file to the hard and reading it which saves you a lot of time and your code becomes neat as well. I have a simple function for that in `deep_utils` library the use case is as follow:
```
from deep_utils import read_img_form
@app.post("/infer", tags=["Inference"])
async def Infer(image: UploadFile = File(...)):
    img = read_img_form(image)
```
you can also wrap the `read_img_form` function with an `async` in a new asynchronous function to utilize `fastapi`'s asynchronous properties.

**Comment by aliaminibagh** [comment]
> 
Pooya thanks for sharing your information with me. I'll work on it.
